-- CREATE DATABASE restaurant_test_ingenosya;
-- \c restaurant_test_ingenosya
------------------------
-------- CONCEPTION ----
------------------------
CREATE SEQUENCE SEQ_COM;

CREATE SEQUENCE SEQ_MENU;

CREATE SEQUENCE SEQ_LGC;

CREATE SEQUENCE SEQ_INGREDIENT;

CREATE SEQUENCE SEQ_MVM;

CREATE SEQUENCE SEQ_REPAS;

CREATE SEQUENCE SEQ_RPM;

CREATE SEQUENCE SEQ_INR;

CREATE TABLE public.COMMANDE (
    COMMANDE_ID VARCHAR(10) DEFAULT 'COM' || NEXTVAL('SEQ_COM') NOT NULL,
    DATE_COMMANDE DATE NOT NULL,
    CONSTRAINT commande_pk PRIMARY KEY (COMMANDE_ID)
);

CREATE TABLE public.MENU (
    MENU_ID VARCHAR(10) DEFAULT 'MNU' || NEXTVAL('SEQ_MENU') NOT NULL,
    DATE_MENU DATE NOT NULL,
    NOM VARCHAR(30) NOT NULL,
    CONSTRAINT menu_pk PRIMARY KEY (MENU_ID)
);

CREATE TABLE public.LIGNE_COMMANDE (
    LGN_COM_ID VARCHAR(10) DEFAULT 'LGC' || NEXTVAL('SEQ_LGC') NOT NULL,
    COMMANDE_ID VARCHAR(10) DEFAULT 'COM' || NEXTVAL('SEQ_COM') NOT NULL,
    MENU_ID VARCHAR(10) DEFAULT 'MNU' || NEXTVAL('SEQ_MENU') NOT NULL,
    QUANTITE_COMMANDE INTEGER NOT NULL,
    CONSTRAINT ligne_commande_pk PRIMARY KEY (LGN_COM_ID)
);

CREATE TABLE public.INGREDIENT (
    INGREDIENT_ID VARCHAR(10) DEFAULT 'ING' || NEXTVAL('SEQ_INGREDIENT') NOT NULL,
    NOM VARCHAR(30) NOT NULL,
    PRIX_ACHAT NUMERIC(15, 3) NOT NULL,
    UNITE VARCHAR(10) NOT NULL,
    CONSTRAINT ingredient_pk PRIMARY KEY (INGREDIENT_ID)
);

CREATE TABLE public.MOUVEMENT_INGREDIENT (
    MVM_ID VARCHAR(10) DEFAULT 'MVM' || NEXTVAL('SEQ_MVM') NOT NULL,
    ENTREE INTEGER NOT NULL,
    SORTIE INTEGER NOT NULL,
    DATE_MVM DATE NOT NULL,
    INGREDIENT_ID VARCHAR(10) DEFAULT 'ING' || NEXTVAL('SEQ_INGREDIENT') NOT NULL,
    CONSTRAINT mouvement_ingredient_pk PRIMARY KEY (MVM_ID)
);

CREATE TABLE public.REPAS (
    REPAS_ID VARCHAR(10) DEFAULT 'RPS' || NEXTVAL('SEQ_REPAS') NOT NULL,
    NOM VARCHAR(30) NOT NULL,
    PRIX_VENTE NUMERIC(15, 3) NOT NULL,
    CONSTRAINT repas_pk PRIMARY KEY (REPAS_ID)
);

CREATE TABLE public.REPAS_MENU (
    RPS_MNU_ID VARCHAR(10) DEFAULT 'RPM' || NEXTVAL('SEQ_RPM') NOT NULL,
    MENU_ID VARCHAR(10) DEFAULT 'MNU' || NEXTVAL('SEQ_MENU') NOT NULL,
    REPAS_ID VARCHAR(10) DEFAULT 'RPS' || NEXTVAL('SEQ_REPAS') NOT NULL,
    QUANTITE_UNITAIRE NUMERIC(10, 3) NOT NULL,
    CONSTRAINT repas_menu_pk PRIMARY KEY (RPS_MNU_ID)
);

CREATE TABLE public.INGREDIENT_REPAS (
    ING_RPS_ID VARCHAR(10) DEFAULT 'INR' || NEXTVAL('SEQ_INR') NOT NULL,
    REPAS_ID VARCHAR(10) DEFAULT 'RPS' || NEXTVAL('SEQ_REPAS') NOT NULL,
    INGREDIENT_ID VARCHAR(10) DEFAULT 'ING' || NEXTVAL('SEQ_INGREDIENT') NOT NULL,
    QUANTITE_UNITAIRE INTEGER NOT NULL,
    CONSTRAINT ningredient_repas_pk PRIMARY KEY (ING_RPS_ID)
);

ALTER TABLE
    public.LIGNE_COMMANDE
ADD
    CONSTRAINT commande_ligne_commande_fk FOREIGN KEY (COMMANDE_ID) REFERENCES public.COMMANDE (COMMANDE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE
    public.REPAS_MENU
ADD
    CONSTRAINT menu_repas_menu_fk FOREIGN KEY (MENU_ID) REFERENCES public.MENU (MENU_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE
    public.LIGNE_COMMANDE
ADD
    CONSTRAINT menu_ligne_commande_fk FOREIGN KEY (MENU_ID) REFERENCES public.MENU (MENU_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE
    public.INGREDIENT_REPAS
ADD
    CONSTRAINT ingredient_ingredient_repas_fk FOREIGN KEY (INGREDIENT_ID) REFERENCES public.INGREDIENT (INGREDIENT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE
    public.MOUVEMENT_INGREDIENT
ADD
    CONSTRAINT ingredient_mouvement_ingredient_fk FOREIGN KEY (INGREDIENT_ID) REFERENCES public.INGREDIENT (INGREDIENT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE
    public.INGREDIENT_REPAS
ADD
    CONSTRAINT repas_ingredient_repas_fk FOREIGN KEY (REPAS_ID) REFERENCES public.REPAS (REPAS_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

ALTER TABLE
    public.REPAS_MENU
ADD
    CONSTRAINT repas_repas_menu_fk FOREIGN KEY (REPAS_ID) REFERENCES public.REPAS (REPAS_ID) ON DELETE NO ACTION ON UPDATE NO ACTION NOT DEFERRABLE;

------------------------
-------- DATA ----------
------------------------
INSERT INTO
    public.INGREDIENT(NOM, PRIX_ACHAT, UNITE)
VALUES
    ('pain burger', 1000, 'unité'),
    ('tomates', 100, 'unité'),
    ('œuf', 1000, 'unité'),
    ('salade', 1000, 'unité'),
    ('oignon', 200, 'unité'),
    ('mortadelle', 5, 'mg'),
    ('pommes de terre', 1, 'g'),
    ('lait', 3, 'ml'),
    ('sucre', 4, 'g'),
    ('yaourt nature', 5, 'ml');

INSERT INTO
    public.REPAS(NOM, PRIX_VENTE)
VALUES
    ('hamburger', 2000),
    ('frites', 1000),
    ('yaourt', 500);

INSERT INTO
    public.INGREDIENT_REPAS(REPAS_ID, INGREDIENT_ID, QUANTITE_UNITAIRE)
VALUES
    ('RPS1', 'ING1', 1),
    ('RPS1', 'ING2', 2),
    ('RPS1', 'ING3', 1),
    ('RPS1', 'ING4', 1),
    ('RPS1', 'ING5', 1),
    ('RPS1', 'ING6', 500),
    ('RPS2', 'ING7', 500),
    ('RPS3', 'ING8', 200),
    ('RPS3', 'ING9', 200),
    ('RPS3', 'ING10', 100);

INSERT INTO
    public.MENU(DATE_MENU, NOM)
VALUES
    ('2021-12-14', 'MENU SOLO'),
    ('2021-12-14', 'MENU DUO');

INSERT INTO
    public.REPAS_MENU(MENU_ID, REPAS_ID, QUANTITE_UNITAIRE)
VALUES
    ('MNU1', 'RPS1', 1),
    ('MNU1', 'RPS2', 1),
    ('MNU1', 'RPS3', 1),
    ('MNU2', 'RPS1', 2),
    ('MNU2', 'RPS2', 2),
    ('MNU2', 'RPS3', 2);


INSERT INTO
    public.MOUVEMENT_INGREDIENT(INGREDIENT_ID, ENTREE, SORTIE, DATE_MVM)
VALUES
    ('ING1', 20, 0, '2021-12-13'),
    ('ING2', 20, 0, '2021-12-13'),
    ('ING3', 20, 0, '2021-12-13'),
    ('ING4', 20, 0, '2021-12-13'),
    ('ING5', 20, 0, '2021-12-13'),
    ('ING6', 2000, 0, '2021-12-13'),
    ('ING7', 2000, 0, '2021-12-13'),
    ('ING8', 2000, 0, '2021-12-13'),
    ('ING9', 2000, 0, '2021-12-13'),
    ('ING10', 2000, 0, '2021-12-13');